import { GoogleGenAI } from "@google/genai";
import { Task } from '../types';
import { PROMPT_TEMPLATES } from '../constants';

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

/**
 * Generates an AI-powered description or text extraction from an image using Google Gemini API.
 * 
 * @param base64Data - The pure base64 string of the image (without data URL header).
 * @param mimeType - The MIME type of the image (e.g., 'image/jpeg', 'image/png').
 * @param task - The type of task to perform (DESCRIBE for description, READ for OCR).
 * @param languageName - The name of the target language for the AI response (e.g., 'Hindi', 'Spanish').
 * 
 * @returns A promise that resolves to the text generated by Gemini AI.
 */
export const generateDescription = async (
    base64Data: string,
    mimeType: string,
    task: Task,
    languageName: string
): Promise<string> => {
    try {
        const fullPrompt = `${PROMPT_TEMPLATES[task]} Please provide the response in ${languageName}.`;

        const imagePart = {
            inlineData: {
                mimeType: mimeType,
                data: base64Data,
            },
        };

        const textPart = {
            text: fullPrompt
        };

        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash',
            contents: { parts: [imagePart, textPart] },
        });

        return response.text;
    } catch (error) {
        console.error("Error calling Gemini API:", error);
        if (error instanceof Error) {
            return `Error: ${error.message}. Please check your API key and network connection.`;
        }
        return "An unknown error occurred while contacting the AI service.";
    }
};
